apiVersion: v1
kind: Pod
metadata:
  name: safe-pod
spec:
  containers:
    - name: analyzer
      image: unprivileged-container:latest
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash", "-c", "sleep 3600"]
